- name: Sample AWX Playbook for Ubuntu Servers
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create a test HTML file
      copy:
        content: "<html><body><h1>Hello from AWX!</h1></body></html>"
        dest: /var/www/html/index.html

    - name: Ensure proper permissions on web content
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes